// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]

export type Experience = Collections['experiences']['schema']['_output']
export declare const experiences: Experience[]

export type Certificate = Collections['certificates']['schema']['_output']
export declare const certificates: Certificate[]

export type Hackathon = Collections['hackathons']['schema']['_output']
export declare const hackathons: Hackathon[]

export type Learning = Collections['learning']['schema']['_output']
export declare const learning: Learning[]

export type Timeline = Collections['timeline']['schema']['_output']
export declare const timeline: Timeline[]
